# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"categorize": "pandas.ipynb",
         "deduplicate": "pandas.ipynb",
         "normalize_col_names": "pandas.ipynb",
         "log_dtypes": "pandas.ipynb",
         "log_transform": "pandas.ipynb",
         "read_files": "pandas.ipynb",
         "localize": "pandas.ipynb",
         "strip_whitespace": "pandas.ipynb",
         "fold": "pandas.ipynb",
         "normalize": "pandas.ipynb",
         "ImgDownloader": "webscraping.ipynb",
         "eikosogram": "data_visualization.ipynb",
         "log_study_wandb": "experiment_tracking_and_hyperparameter_optimization.ipynb",
         "dash_ctx": "plotly_dash.ipynb",
         "idify": "plotly_dash.ipynb",
         "flatten": "300_misc.ipynb",
         "DotDict": "307_utils.ipynb",
         "suppress_stdout": "300_misc.ipynb",
         "Show": "300_misc.ipynb",
         "coalesce": "307_utils.ipynb",
         "show_plotly": "300_misc.ipynb",
         "Hook": "300_misc.ipynb",
         "HookBwd": "300_misc.ipynb",
         "Learner.show_activations": "300_misc.ipynb",
         "decorate_all_methods_with": "307_utils.ipynb",
         "decorate_function_with": "307_utils.ipynb",
         "dict_generator": "307_utils.ipynb",
         "async_map": "302_asyncio.ipynb",
         "load_config": "307_utils.ipynb"}

modules = ["pandas.py",
           "webscraping.py",
           "data_visualization.py",
           "experiment_tracking.py",
           "plotly_dash.py",
           "misc.py",
           "asyncio.py",
           "utils.py"]

doc_url = "https://andrewtruong.github.io/notes/"

git_url = "https://github.com/andrewtruong/notes/tree/master/"

def custom_doc_links(name): return None
