# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_other/302_asyncio.ipynb (unless otherwise specified).

__all__ = ['async_map']

# Cell
import asyncio
from tqdm.auto import tqdm

async def async_map(coroutine, iterable, pool_size=2, tqdm_kwargs={}, *args, **kwargs):
    semaphore = asyncio.Semaphore(pool_size)
    async def sem_task(task):
        async with semaphore:
            return await task

    tasks = [coroutine(param, *args, **kwargs) for param in iterable]

    with tqdm(asyncio.as_completed(tasks), ncols='100%', **tqdm_kwargs) as pbar:
        results = [await sem_task(task) for task in pbar]
        return results