# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_modeling/data_visualization.ipynb (unless otherwise specified).

__all__ = ['eikosogram']

# Cell
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import numpy as np

from .misc import show_plotly

# Cell
def eikosogram(df:pd.DataFrame, x:str, color:str, freq:str):
    '''
    Given a dataframe and two parameters, x and color, return an Eikosogram
    '''
    base = df.groupby(x)[freq].sum() / df.groupby(x)[freq].sum().sum()
    labels = base.index.values
    widths = base.values

    base2 = df.pivot_table(index=x, columns=color, values=freq, aggfunc='sum')
    base2 = (base2.T / base2.sum(axis=1)).T
    data = {col: base2[col].values for col in base2}

    fig = go.Figure()
    for key in data:
        fig.add_trace(go.Bar(
            name=key,
            y=data[key],
            x=np.cumsum(widths)-widths,
            width=widths,
            offset=0,
            customdata=np.transpose([labels, widths*data[key]]),
            texttemplate="%{y} x %{width} =<br>%{customdata[1]}",
            textposition="inside",
            textangle=0,
            textfont_color="white",
            hovertemplate="<br>".join([
                "label: %{customdata[0]}",
                "width: %{width}",
                "height: %{y}",
                "area: %{customdata[1]}",
            ])
        ))

    fig.update_xaxes(
        tickvals=np.cumsum(widths)-widths/2,
        ticktext=[f'{l}<br>{w:.2%}' for l,w in zip(labels, widths)],
        range=[0,1]
    ).update_yaxes(
        tickformat='.2%',
        range=[0,1]
    ).update_layout(
        title_text="Eikosogram",
        barmode="stack",
        uniformtext=dict(mode="hide", minsize=5),
    )

    return fig