# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_data_science/hyperparameter_optimization.ipynb (unless otherwise specified).

__all__ = ['log_study_wandb']

# Cell
import lightgbm as lgb
import pandas as pd
from .pandas import categorize
from sklearn.metrics import mean_squared_error as mse
from sklearn.model_selection import train_test_split
import optuna
import wandb
from .misc import show_plotly

# Cell
def log_study_wandb(study, value_name=None, wandb_kwargs={}):
    results = study.trials_dataframe().drop(['number', 'state'], axis=1)
    results.duration = results.duration.dt.total_seconds()
    if value_name:
        results = results.rename({'value': value_name}, axis=1)

    with wandb.init(**wandb_kwargs) as w:
        for i, vals in results.iterrows():
            w.log(vals.to_dict(), step=i)