# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_build_and_deploy_data_apps/plotly_dash.ipynb (unless otherwise specified).

__all__ = ['dash_ctx', 'idify']

# Cell
from functools import wraps

def dash_ctx(inputs):
    '''
    Provide a ctx dict to use in the dash callback system.

    For example:
    ```python
    import dash
    from dash.dependencies import Input, Output, State

    app = dash.Dash('app')

    outputs = [Output('main-div', 'children')]
    inputs = [Input('selector1', 'value'), Input('selector2', 'value')]
    states = [State('selector3', 'value')]

    @app.callback(outputs, inputs, states)
    @dash_ctx(inputs + states)
    def update(**ctx):
        pass
        # do something with ctx['selector1'], ctx['selector2'], ctx['selector3']
    ```
    '''
    def accept_func(func):
        @wraps(func)
        def wrapper(*args):
            input_names = [item.component_id for item in inputs]
            kwargs_dict = dict(zip(input_names, args))
            return func(**kwargs_dict)
        return wrapper
    return accept_func

# Cell
def idify(name):
    'Helper function to convert human labels to HTML ids'
    return name.lower().replace(" ", "-")